services:
  ha-dashboard:
    build:
      context: .
      args:
        # Build-time environment variables for Vite
        # These will be baked into the built app
        - VITE_HA_URL=${VITE_HA_URL}
        - VITE_HA_TOKEN=${VITE_HA_TOKEN}
        - VITE_OPENWEATHER_API_KEY=${VITE_OPENWEATHER_API_KEY}
    container_name: ha-dashboard
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Persist dashboard configurations
      - ha-dashboard-data:/app/dist/data/dashboards
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3001/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ha-network

volumes:
  ha-dashboard-data:
    driver: local

networks:
  ha-network:
    driver: bridge
